/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteRouteImport } from './routes/_portal/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as PortalProfileIndexRouteImport } from './routes/_portal/profile/index'
import { Route as PortalPostsIndexRouteImport } from './routes/_portal/posts/index'
import { Route as PortalFeedIndexRouteImport } from './routes/_portal/feed/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PortalPostsPostIdRouteImport } from './routes/_portal/posts/$postId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalProfileIndexRoute = PortalProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPostsIndexRoute = PortalPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalFeedIndexRoute = PortalFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPostsPostIdRoute = PortalPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => PortalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AdminDashboardRoute
  '/posts/$postId': typeof PortalPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/feed': typeof PortalFeedIndexRoute
  '/posts': typeof PortalPostsIndexRoute
  '/profile': typeof PortalProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AdminDashboardRoute
  '/posts/$postId': typeof PortalPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/feed': typeof PortalFeedIndexRoute
  '/posts': typeof PortalPostsIndexRoute
  '/profile': typeof PortalProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_portal/posts/$postId': typeof PortalPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_portal/feed/': typeof PortalFeedIndexRoute
  '/_portal/posts/': typeof PortalPostsIndexRoute
  '/_portal/profile/': typeof PortalProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/posts/$postId'
    | '/api/auth/$'
    | '/feed'
    | '/posts'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/posts/$postId'
    | '/api/auth/$'
    | '/feed'
    | '/posts'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_portal'
    | '/login'
    | '/signup'
    | '/_admin/dashboard'
    | '/_portal/posts/$postId'
    | '/api/auth/$'
    | '/_portal/feed/'
    | '/_portal/posts/'
    | '/_portal/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_portal/profile/': {
      id: '/_portal/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/posts/': {
      id: '/_portal/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PortalPostsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/feed/': {
      id: '/_portal/feed/'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof PortalFeedIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/posts/$postId': {
      id: '/_portal/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PortalPostsPostIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalPostsPostIdRoute: typeof PortalPostsPostIdRoute
  PortalFeedIndexRoute: typeof PortalFeedIndexRoute
  PortalPostsIndexRoute: typeof PortalPostsIndexRoute
  PortalProfileIndexRoute: typeof PortalProfileIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalPostsPostIdRoute: PortalPostsPostIdRoute,
  PortalFeedIndexRoute: PortalFeedIndexRoute,
  PortalPostsIndexRoute: PortalPostsIndexRoute,
  PortalProfileIndexRoute: PortalProfileIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
