/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetApprovalRouteImport } from './routes/get-approval'
import { Route as PortalRouteRouteImport } from './routes/_portal/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as PortalProfileIndexRouteImport } from './routes/_portal/profile/index'
import { Route as PortalPostsIndexRouteImport } from './routes/_portal/posts/index'
import { Route as PortalFeedIndexRouteImport } from './routes/_portal/feed/index'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users/index'
import { Route as AdminManagePostsIndexRouteImport } from './routes/_admin/manage-posts/index'
import { Route as AdminAudioPresetsIndexRouteImport } from './routes/_admin/audio-presets/index'
import { Route as SharePostsPostIdRouteImport } from './routes/share/posts/$postId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PortalProfileUserIdRouteImport } from './routes/_portal/profile/$userId'
import { Route as PortalPostsPostIdRouteImport } from './routes/_portal/posts/$postId'
import { Route as AdminUsersUserIdRouteImport } from './routes/_admin/users/$userId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetApprovalRoute = GetApprovalRouteImport.update({
  id: '/get-approval',
  path: '/get-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalProfileIndexRoute = PortalProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPostsIndexRoute = PortalPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalFeedIndexRoute = PortalFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManagePostsIndexRoute = AdminManagePostsIndexRouteImport.update({
  id: '/manage-posts/',
  path: '/manage-posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAudioPresetsIndexRoute = AdminAudioPresetsIndexRouteImport.update({
  id: '/audio-presets/',
  path: '/audio-presets/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SharePostsPostIdRoute = SharePostsPostIdRouteImport.update({
  id: '/share/posts/$postId',
  path: '/share/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileUserIdRoute = PortalProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPostsPostIdRoute = PortalPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-approval': typeof GetApprovalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AdminDashboardRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/posts/$postId': typeof PortalPostsPostIdRoute
  '/profile/$userId': typeof PortalProfileUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/share/posts/$postId': typeof SharePostsPostIdRoute
  '/audio-presets': typeof AdminAudioPresetsIndexRoute
  '/manage-posts': typeof AdminManagePostsIndexRoute
  '/users': typeof AdminUsersIndexRoute
  '/feed': typeof PortalFeedIndexRoute
  '/posts': typeof PortalPostsIndexRoute
  '/profile': typeof PortalProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-approval': typeof GetApprovalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AdminDashboardRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/posts/$postId': typeof PortalPostsPostIdRoute
  '/profile/$userId': typeof PortalProfileUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/share/posts/$postId': typeof SharePostsPostIdRoute
  '/audio-presets': typeof AdminAudioPresetsIndexRoute
  '/manage-posts': typeof AdminManagePostsIndexRoute
  '/users': typeof AdminUsersIndexRoute
  '/feed': typeof PortalFeedIndexRoute
  '/posts': typeof PortalPostsIndexRoute
  '/profile': typeof PortalProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_portal': typeof PortalRouteRouteWithChildren
  '/get-approval': typeof GetApprovalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_portal/posts/$postId': typeof PortalPostsPostIdRoute
  '/_portal/profile/$userId': typeof PortalProfileUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/share/posts/$postId': typeof SharePostsPostIdRoute
  '/_admin/audio-presets/': typeof AdminAudioPresetsIndexRoute
  '/_admin/manage-posts/': typeof AdminManagePostsIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
  '/_portal/feed/': typeof PortalFeedIndexRoute
  '/_portal/posts/': typeof PortalPostsIndexRoute
  '/_portal/profile/': typeof PortalProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-approval'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/users/$userId'
    | '/posts/$postId'
    | '/profile/$userId'
    | '/api/auth/$'
    | '/share/posts/$postId'
    | '/audio-presets'
    | '/manage-posts'
    | '/users'
    | '/feed'
    | '/posts'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-approval'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/users/$userId'
    | '/posts/$postId'
    | '/profile/$userId'
    | '/api/auth/$'
    | '/share/posts/$postId'
    | '/audio-presets'
    | '/manage-posts'
    | '/users'
    | '/feed'
    | '/posts'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_portal'
    | '/get-approval'
    | '/login'
    | '/signup'
    | '/_admin/dashboard'
    | '/_admin/users/$userId'
    | '/_portal/posts/$postId'
    | '/_portal/profile/$userId'
    | '/api/auth/$'
    | '/share/posts/$postId'
    | '/_admin/audio-presets/'
    | '/_admin/manage-posts/'
    | '/_admin/users/'
    | '/_portal/feed/'
    | '/_portal/posts/'
    | '/_portal/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  GetApprovalRoute: typeof GetApprovalRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SharePostsPostIdRoute: typeof SharePostsPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-approval': {
      id: '/get-approval'
      path: '/get-approval'
      fullPath: '/get-approval'
      preLoaderRoute: typeof GetApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_portal/profile/': {
      id: '/_portal/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/posts/': {
      id: '/_portal/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PortalPostsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/feed/': {
      id: '/_portal/feed/'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof PortalFeedIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/manage-posts/': {
      id: '/_admin/manage-posts/'
      path: '/manage-posts'
      fullPath: '/manage-posts'
      preLoaderRoute: typeof AdminManagePostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/audio-presets/': {
      id: '/_admin/audio-presets/'
      path: '/audio-presets'
      fullPath: '/audio-presets'
      preLoaderRoute: typeof AdminAudioPresetsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/share/posts/$postId': {
      id: '/share/posts/$postId'
      path: '/share/posts/$postId'
      fullPath: '/share/posts/$postId'
      preLoaderRoute: typeof SharePostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/profile/$userId': {
      id: '/_portal/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof PortalProfileUserIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/posts/$postId': {
      id: '/_portal/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PortalPostsPostIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_admin/users/$userId': {
      id: '/_admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminAudioPresetsIndexRoute: typeof AdminAudioPresetsIndexRoute
  AdminManagePostsIndexRoute: typeof AdminManagePostsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminAudioPresetsIndexRoute: AdminAudioPresetsIndexRoute,
  AdminManagePostsIndexRoute: AdminManagePostsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalPostsPostIdRoute: typeof PortalPostsPostIdRoute
  PortalProfileUserIdRoute: typeof PortalProfileUserIdRoute
  PortalFeedIndexRoute: typeof PortalFeedIndexRoute
  PortalPostsIndexRoute: typeof PortalPostsIndexRoute
  PortalProfileIndexRoute: typeof PortalProfileIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalPostsPostIdRoute: PortalPostsPostIdRoute,
  PortalProfileUserIdRoute: PortalProfileUserIdRoute,
  PortalFeedIndexRoute: PortalFeedIndexRoute,
  PortalPostsIndexRoute: PortalPostsIndexRoute,
  PortalProfileIndexRoute: PortalProfileIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  GetApprovalRoute: GetApprovalRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SharePostsPostIdRoute: SharePostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
